import hashlib
import logging
import os
import uuid

from django.conf import settings
from django.core.cache import cache

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None
    types = None

logger = logging.getLogger(__name__)


def _cache_key(prompt: str) -> str:
    h = hashlib.sha256(prompt.strip().lower().encode()).hexdigest()[:16]
    return f"gemini:image:{h}"


def generate_job_image(prompt: str) -> str:
    """Generate an image for a job posting using Gemini's image model.

    Returns the relative media URL of the saved image.
    """
    # Check cache
    key = _cache_key(prompt)
    cached = cache.get(key)
    if cached is not None:
        return cached

    api_key = getattr(settings, 'GEMINI_API_KEY', None)
    if not api_key:
        raise ValueError("GEMINI_API_KEY is not configured")

    if genai is None:
        raise ValueError("google-genai package is not installed")

    client = genai.Client(api_key=api_key)

    image_prompt = (
        f"Create a friendly, colorful illustration for a volunteer job posting: {prompt}. "
        "Style: flat vector illustration, warm colors, community-oriented, no text."
    )

    response = client.models.generate_content(
        model='gemini-2.5-flash-image',
        contents=image_prompt,
        config=types.GenerateContentConfig(
            response_modalities=['IMAGE'],
        ),
    )

    # Extract the image data from the response
    image_data = None
    if response.candidates:
        for part in response.candidates[0].content.parts:
            if part.inline_data is not None:
                image_data = part.inline_data.data
                break

    if image_data is None:
        raise ValueError("No image was generated by the model")

    # Save to disk
    media_root = getattr(settings, 'MEDIA_ROOT', '')
    image_dir = os.path.join(media_root, 'job_images')
    os.makedirs(image_dir, exist_ok=True)

    filename = f"{uuid.uuid4().hex}.png"
    filepath = os.path.join(image_dir, filename)

    with open(filepath, 'wb') as f:
        f.write(image_data)

    relative_url = f"/media/job_images/{filename}"

    # Cache for 1 hour
    cache.set(key, relative_url, timeout=3600)

    return relative_url
