# Generated by Django 6.0.1 on 2026-02-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_jobacceptance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobacceptance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("dropped", "Dropped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
