# Generated by Django 5.2 on 2026-02-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0005_add_location_privacy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
